models:
  - "TaylorAI/gte-tiny"
  - "thenlper/gte-small"
  - "sentence-transformers/distiluse-base-multilingual-cased-v2"
  - "intfloat/multilingual-e5-small"
params:
  batch_size: [1,2,4,8,16,32,64]
  clip_str: [1024, 2048, 100000]
  seq_len: [128, 512]
input: "/root/input.txt"
output: "/root/stats.tsv"
docs_count: 1000
num_runs: 10