models:
  onnx:
    - "TaylorAI/gte-tiny"
    - "intfloat/multilingual-e5-small"
  vanilla:
    - "TaylorAI/gte-tiny"
    - "thenlper/gte-small"
    - "sentence-transformers/distiluse-base-multilingual-cased-v2"
    - "intfloat/multilingual-e5-small"
params:
  batch_size: [1, 4, 8, 16, 32, 64]
  clip_str: [1024]
  seq_len: [128]
input: "/root/encoder_speed_test/input.txt"
output: "/root/encoder_speed_test/stats.tsv"
docs_count: 1000
num_runs: 5
